version: "3.9"
services:
  fastapi:
    volumes:
      - .:/app:cached           # Mount project into /app inside container
#    command for allow debugging      
#    command: >
#      sh -c "python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"              # FastAPI app
      - "5678:5678"              # Debugpy (if you want debugging)
